// <auto-generated />
using System;
using Hr.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hr.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260917182839_AddSeedData")]
    partial class AddSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hr.Domain.Entities.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset(0)")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("ReviewerNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("StartDate");

                    b.HasIndex("EmployeeId", "Status");

                    b.HasIndex("EmployeeId", "StartDate", "EndDate")
                        .IsUnique()
                        .HasFilter("[Status] = 'Pending'");

                    b.ToTable("LeaveRequests", null, t =>
                        {
                            t.HasCheckConstraint("CK_LeaveRequests_DateRange", "[EndDate] >= [StartDate]");

                            t.HasCheckConstraint("CK_LeaveRequests_EmployeeId", "[EmployeeId] > 0");

                            t.HasCheckConstraint("CK_LeaveRequests_Status", "[Status] IN ('Pending','Approved','Rejected')");

                            t.HasCheckConstraint("CK_LeaveRequests_Type", "[Type] IN ('Vacation','Sick','Unpaid')");
                        });

                    b.HasData(
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 2, 10, 9, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EmployeeId = 1,
                            EndDate = new DateOnly(2026, 3, 6),
                            ReviewerNote = "Approved; cover arranged with the team.",
                            StartDate = new DateOnly(2026, 3, 2),
                            Status = "Approved",
                            Type = "Vacation"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 16, 7, 40, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EmployeeId = 2,
                            EndDate = new DateOnly(2026, 3, 18),
                            ReviewerNote = "Medical certificate received.",
                            StartDate = new DateOnly(2026, 3, 16),
                            Status = "Approved",
                            Type = "Sick"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 20, 11, 5, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EmployeeId = 3,
                            EndDate = new DateOnly(2026, 4, 10),
                            StartDate = new DateOnly(2026, 4, 6),
                            Status = "Pending",
                            Type = "Vacation"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 13, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EmployeeId = 4,
                            EndDate = new DateOnly(2026, 4, 13),
                            ReviewerNote = "No notice given and no certificate provided.",
                            StartDate = new DateOnly(2026, 4, 13),
                            Status = "Rejected",
                            Type = "Sick"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 2, 14, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EmployeeId = 5,
                            EndDate = new DateOnly(2026, 5, 15),
                            StartDate = new DateOnly(2026, 5, 4),
                            Status = "Pending",
                            Type = "Unpaid"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 4, 28, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EmployeeId = 6,
                            EndDate = new DateOnly(2026, 5, 20),
                            StartDate = new DateOnly(2026, 5, 18),
                            Status = "Pending",
                            Type = "Vacation"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 1, 6, 50, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EmployeeId = 7,
                            EndDate = new DateOnly(2026, 6, 5),
                            ReviewerNote = "Approved; workload reassigned.",
                            StartDate = new DateOnly(2026, 6, 1),
                            Status = "Approved",
                            Type = "Sick"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 30, 16, 20, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EmployeeId = 8,
                            EndDate = new DateOnly(2026, 6, 26),
                            ReviewerNote = "Peak delivery week; please reschedule.",
                            StartDate = new DateOnly(2026, 6, 22),
                            Status = "Rejected",
                            Type = "Vacation"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 6, 10, 9, 45, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EmployeeId = 9,
                            EndDate = new DateOnly(2026, 7, 17),
                            StartDate = new DateOnly(2026, 7, 6),
                            Status = "Pending",
                            Type = "Vacation"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 7, 1, 13, 10, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EmployeeId = 10,
                            EndDate = new DateOnly(2026, 7, 21),
                            StartDate = new DateOnly(2026, 7, 20),
                            Status = "Pending",
                            Type = "Unpaid"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
